domain: "volodya-leveryev.github.io"
baseurl: ""
url: "https://volodya-leveryev.github.io"
destination: "./docs"
collections:
  linux:
    output: true
  windows:
    output: true
  msa:
    output: true
  patterns:
    output: true
