name: Build and Deploy
on: [push]
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          mkdir out/
          touch out/.nojekyll
          npm ci
          npm run build
          npm run export

      - uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: out/
